name: aifit
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animated_custom_dropdown: ^3.1.1
  battery_plus: ^6.0.3
  cloud_firestore: ^5.5.0
  csv:
  dartz: ^0.10.1
  device_info_plus: ^10.1.2
  equatable: ^2.0.5
  flutter_hooks:
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  flutter_activity_recognition: ^3.1.0
  flutter_riverpod: ^2.5.1
  freezed_annotation:
  go_router:
  hooks_riverpod: ^2.5.1
  just_audio: ^0.9.39
  intl:
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logger: ^2.4.0
  path_provider:
  permission_handler:
  riverpod_annotation: ^2.3.5
  rxdart: ^0.28.0
  # move this into external library
  sensors_plus: ^6.0.1
  share_plus:
  shared_preferences: ^2.3.2
  material_table_view: ^5.0.0
  wakelock_plus:

dependency_overrides:
  analyzer: ^6.5.0
  meta: ^1.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  custom_lint:
  flutter_lints: ^3.0.0
  freezed:
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/images/